const healthcarePositions = [ 
    "Nurse", 
    "Physiotherapist", 
    "Dermatologist", 
    "Dentist", 
    "General Practitioner", 
    "Surgeon", 
    "Pediatrician", 
    "Cardiologist", 
    "Radiologist", 
    "Anesthesiologist", 
    "Pharmacist", 
    "Psychiatrist", 
    "Psychologist", 
    "Occupational Therapist", 
    "Speech Therapist", 
    "Optometrist",
    "Ophthalmologist", 
    "Orthopedic Surgeon", 
    "Gynecologist", 
    "Obstetrician", 
    "Oncologist", 
    "Nephrologist", 
    "Neurologist", 
    "Endocrinologist", 
    "Gastroenterologist", 
    "Hematologist", 
    "Infectious Disease Specialist", 
    "Pulmonologist", 
    "Rheumatologist", 
    "Urologist", 
    "Emergency Medicine Physician", 
    "Family Medicine Physician", 
    "Internal Medicine Physician", 
    "Pathologist", 
    "Chiropractor", 
    "Dietitian", 
    "Medical Laboratory Technician", 
    "Medical Assistant", 
    "Paramedic", 
    "Respiratory Therapist", 
    "Clinical Research Coordinator", 
    "Genetic Counselor", 
    "Health Information Technician", 
    "Medical Transcriptionist", 
    "Radiologic Technologist", 
    "Sonographer", 
    "Surgical Technologist", 
    "Veterinarian" 
];

export default healthcarePositions;